# Generated by Django 4.1.5 on 2023-02-05 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Trail'), (2, 'Basic'), (3, 'Advance'), (3, 'Pro')], default=1),
        ),
    ]
