# Generated by Django 4.1.5 on 2023-02-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
