# Generated by Django 4.1.5 on 2023-02-17 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_company_userprivacymodelprompt_userprompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprompt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
