# Generated by Django 4.1.5 on 2023-02-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_user_api_total_requests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_total_requests',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
