# Generated by Django 4.1.5 on 2023-03-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0009_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailQue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('sender', models.CharField(max_length=200)),
                ('recipient_list', models.JSONField(default=list)),
                ('sent', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
