# Generated by Django 4.1.5 on 2023-03-09 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0014_usersettings_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersettings',
            unique_together={('user', 'key')},
        ),
    ]
