# Generated by Django 4.1.5 on 2023-03-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0016_rename_usersettings_usersetting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gaia_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['domain'], name='new_app_com_domain_ee7c89_idx'),
        ),
    ]
